name: "Bartek Kruszczy≈Ñski | Developer, Car Nut, dnb lover"
markdown: redcarpet
pygments: true
assets:
  js_compressor:  uglifier
  css_compressor: yui
exclude: vendor Gemfile Gemfile.lock Procfile config.ru

